### ISSUE TITLE
Give the generated class a package name

### ISSUE THREAD

**Issue by danielcompton** [apa512/rethinkdb-protobuf#1]
It looks a little bit odd that the generated class doesn't have a Java package and is just a bare class. While I can't think of any problems of doing this in Clojure, it's generally not good to do this. This would also make this class reusable for other Java libraries. One possibility is to do what this Java driver did and add a package declaration to the proto file: https://github.com/npiv/rethink-java-driver/blob/master/src/main/proto/q2l.proto#L1

I'm not an expert on protocol buffers and haven't looked too deeply into lein-protobuf to see what the options are there or how other people do it. What are your thoughts?

**Comment by apa512** [comment]
I've stayed away from Java and have no idea what packages are good for. So you're saying I should just add something like `option java_package = "com.rethinkdb.proto";` to the proto file?

**Comment by danielcompton** [comment]
I just took a look at how the Java libraries did it and saw that method. That looks like a library specific extension though, so I suspect it wouldn't work in our case. I'll take a look at the Clojure protobuf library to see how to do it in Clojure.

**Comment by danielcompton** [comment]
I think `package` is the right one to use as it's generic for all Protocol buffer implementations. `java_package` is an override for Java specifically. I'll ask the RethinkDB dev about updating this because it probably should come from them.
